In [1]:
import numpy as np


In [2]:
np.__version__

'2.2.0'

In [ ]:
numere = [1, 2, 3, 4, 5]

In [3]:
colectie = ["ianrna", "vara", "toamna"]
arr = np.array(colectie)
print("arr = ", arr)
print("type arr = ", type(arr))



arr =  ['ianrna' 'vara' 'toamna']
type arr =  <class 'numpy.ndarray'>


In [6]:
arr = np.array([20, 30, 40,])
arr, arr.dtype

(array([20, 30, 40]), dtype('int64'))

In [7]:
arr = np.array([20, 30, 40,], dtype=np.int8)
arr, arr.dtype

(array([20, 30, 40], dtype=int8), dtype('int8'))

In [8]:
arr = np.array([20, 30, 128,], dtype=np.int8)
arr, arr.dtype

OverflowError: Python integer 128 out of bounds for int8

In [9]:
arr = np.array([20, 30, 128,], dtype=np.uint8)
arr, arr.dtype

(array([ 20,  30, 128], dtype=uint8), dtype('uint8'))

In [10]:
arr = np.array([20, 30, 256,], dtype=np.uint8)
arr, arr.dtype

OverflowError: Python integer 256 out of bounds for uint8