In [1]:
import numpy as np

In [2]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [6]:
np.arange(5, 11, 2)

array([5, 7, 9])

In [11]:
arr = np.arange(5, 11, 2)
print(arr)
print("maxim = ",arr.max())
print("minim = ", arr.min())
print("lungime = ", arr.size)



[5 7 9]
maxim =  9
minim =  5
lungime =  3


In [12]:
arr = np.arange(5, 11, 2)
print(arr)
print("maxim = ",max(arr))
print("minim = ", min(arr))
print("lungime = ", len(arr))

[5 7 9]
maxim =  9
minim =  5
lungime =  3


In [13]:
arr = np.arange(5, 11, 2)
print(arr)
print("argmax = ", arr.argmax()) #unde gasesc pozitia celui mai mare numar

[5 7 9]
argmax =  2


In [14]:
arr = np.arange(5, 11, 2)
print(arr)
print("argmin = ", arr.argmin()) #unde gasesc pozitia celui mai mic numar

[5 7 9]
argmin =  0


In [17]:
arr = np.arange(10, 100, 5)
arr[:5:2]

array([10, 20, 30])

In [18]:
arr = np.arange(10, 100, 5)
arr + arr

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
       150, 160, 170, 180, 190])

In [23]:
arr = np.arange(1, 11)
print(arr)
print(arr + arr)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
arr = np.arange(1, 11)
arr = arr / 2
print(arr)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [26]:
arr = np.arange(1, 11)
arr = arr > 2
print(arr)

[False False  True  True  True  True  True  True  True  True]


In [28]:
arr = range (1, 11)
list(map(lambda x: x>2, arr))

[False, False, True, True, True, True, True, True, True, True]

In [29]:
arr = range(1, 11)
list(filter(lambda x: x > 2, arr))


[3, 4, 5, 6, 7, 8, 9, 10]

In [30]:
arr = np.arange(1, 11)
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr = np.arange(1, 11)
arr[arr % 3 != 0]

array([ 1,  2,  4,  5,  7,  8, 10])

In [32]:
arr = np.arange(1, 11)
arr[arr % 3 == 0]

array([3, 6, 9])

In [35]:
arr = np.arange(1, 11)
arr[(arr % 3 != 0) & (arr > 5)]

array([ 7,  8, 10])

In [36]:
arr = np.arange(1, 11)
nedivizibile_cu_3 = arr % 3 != 0
mai_mari_ca_5 = arr > 5
arr[nedivizibile_cu_3 & mai_mari_ca_5]

array([ 7,  8, 10])

& = AND

In [37]:
arr = np.arange(1, 11)
nedivizibile_cu_3 = arr % 3 != 0
mai_mari_ca_5 = arr > 5
arr[nedivizibile_cu_3 | mai_mari_ca_5]

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

| = OR