In [2]:
import numpy as np
np.__version__

'2.2.0'

In [1]:
######### Exercitiul ################
# Creați un vector cu 10 elemente întregi, toate fiind egale cu 0.

In [5]:
arr = np.zeros(10, dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
######### Exercitiul ################
# Creați un vector cu 10 elemente întregi, toate fiind egale cu 1.

In [6]:
arr = np.ones(10, dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [3]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 0 la 9.

In [9]:
arr = np.arange(0, 10, dtype = int)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 10 la 29.

In [10]:
arr = np.arange(10, 30, dtype = int)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [5]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 0 la 9 în ordine inversă.

In [13]:
arr = np.arange(9, -1, -1, dtype = int)
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
######### Exercitiul ################
# Creați un vector cu 10 elemente aleatoare între 0 și 1.

In [19]:
arr = np.random.random(10)
arr

array([0.35680724, 0.94095185, 0.47876482, 0.31526372, 0.4153219 ,
       0.71334478, 0.09063193, 0.8216323 , 0.74999959, 0.68732545])

In [20]:
help(np.random.random)

Help on method random in module numpy.random:

random(size=None) method of numpy.random.mtrand.RandomState instance
    random(size=None)

    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [7]:
######### Exercitiul ################
# Creați o matrice 3x3 cu elemente întregi aleatoare între 0 și 9.

In [44]:
arr = np.random.randint(0,9,(3,3))
arr

array([[7, 6, 7],
       [6, 0, 8],
       [4, 5, 4]], dtype=int32)

In [8]:
######### Exercitiul ################
# Creați o matrice identitate 5x5.

In [29]:
arr = np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
######### Exercitiul ################
# Adunați două matrici de dimensiuni egale (de exemplu, 3x3).

In [36]:
arr = np.ones(9, dtype=int).reshape(3,3)
arr_1 = arr
arr_2 = arr*2

print("arr_1 =",arr_1)
print("arr_2 =",arr_2)
print("arr_1 + arr_2 =",arr_1 + arr_2)


arr_1 = [[1 1 1]
 [1 1 1]
 [1 1 1]]
arr_2 = [[2 2 2]
 [2 2 2]
 [2 2 2]]
arr_1 + arr_2 = [[3 3 3]
 [3 3 3]
 [3 3 3]]


In [10]:
######### Exercitiul ################
# Înmulțiți două matrici de dimensiuni corespunzătoare (de  exemplu, 2x3 și 3x2).

In [46]:
arr_1 = np.ones(6).reshape(2,3)
arr_2 = np.ones(6).reshape(3,2)

print("arr_1 = ", arr_1)
print("arr_2 = ", arr_2)
print("arr_1 * arr_2", np.dot(arr_1, arr_2))

arr_1 =  [[1. 1. 1.]
 [1. 1. 1.]]
arr_2 =  [[1. 1.]
 [1. 1.]
 [1. 1.]]
arr_1 * arr_2 [[3. 3.]
 [3. 3.]]


In [11]:
######### Exercitiul ################
# Transpuneți o matrice (de exemplu, 3x4).

In [50]:
arr = np.random.randint(0,10,(3,4))
print(arr)
print(arr.T)

[[8 1 0 2]
 [5 5 7 6]
 [1 2 0 4]]
[[8 5 1]
 [1 5 2]
 [0 7 0]
 [2 6 4]]


In [12]:
######### Exercitiul ################
# Găsiți valoarea maximă dintr-un vector.

In [55]:
arr = np.random.randint(0,10,(1,10))
print(arr)
print("valoarea maxima este",arr.max())
print("la indexul", arr.argmax())


[[1 0 4 9 0 3 0 2 6 7]]
valoarea maxima este 9
la indexul 3


In [13]:
######### Exercitiul ################
# Găsiți indicele valorii maxime dintr-un vector.

In [14]:
######### Exercitiul ################
# Găsiți media aritmetică a valorilor dintr-o matrice.

In [58]:
arr = np.random.randint(0,10,(1,10))
print(arr)
print("Media este", arr.mean())

[[9 6 3 6 8 0 9 7 0 0]]
Media este 4.8
